

/* header definition begin                   Don't remove this line*/ 
#include "vdcl\ram.vdcl.h"
#include "vdcl\vmstram.vdcl.h"
#include "vdcl\vmsn_io_ram.vdcl.h"
#include "vdcl\baurom.vdcl.h"
#include "vdcl\sysram.vdcl.h"
#include "vdcl\flr_nvm.vdcl.h"
#include "vdcl\fcrm_claw_ram.vdcl.h"
#include "vdcl\claw_fcrm_ram.vdcl.h"
#include "vdcl\fcrm_nvm_ram.vdcl.h"

/* header definition end                   Don't remove this line*/ 
/* declaration  begin                  Don't remove this line */ 
VDCL_acon_ccdl_status;           /*辅助控制器数据CCDL有效状态               */
VDCL_ads_ccdl_status;        /*大气数据CCDL有效状态                  */
VDCL_aq_ram;        /*俯仰速率                          */
VDCL_ccdl_buf;        /*总线数据缓冲区                       */
VDCL_ch_health;        /*CCDL & S/W & H/W status       */
VDCL_dltwowsw_ram;        /*左轮载开关                         */
VDCL_etcl_ccdl_status;        /*ETCL数据CCDL有效状态                */
VDCL_etcr_ccdl_status;        /*ETCR数据CCDL有效状态                */
VDCL_FCRM_FTI1;
VDCL_FCRM_FTI2;
VDCL_FCRM_FTI3;
VDCL_FCRM_FTI4;
VDCL_FCRM_FTI5;
VDCL_FCRM_FTI6;
VDCL_FCRM_FTI7;
VDCL_FCRM_FTI8;
VDCL_fcrm_sys_ccount;        /*FCRM分区内的系统计数器值                */
VDCL_flr_nvm_fcrm;
VDCL_ins_ccdl_status;        /*惯导数据CCDL有效状态                  */
VDCL_isacb_ccdl_status;        /*后作动器控制器数据CCDL有效状态             */
VDCL_isacf_ccdl_status;        /*前作动器控制器数据CCDL有效状态             */
VDCL_mo_cl_rcf2;        /*控制律重构字2                       */
VDCL_mo_cl_rcnf;        /*控制律重构字1                       */
VDCL_mo_ocm_stat;        /*status of output commands     */
VDCL_out_cmd_lst;        /*输出指令缓冲区                       */
VDCL_piu_ccdl_status;        /*PIU数据CCDL有效状态                 */
VDCL_totalbaupkg0;
VDCL_totalbaupkg1;
VDCL_totalbaupkg2;
VDCL_totalbaupkg3;
VDCL_totalbaupkgdesaddr0;
VDCL_totalbaupkgdesaddr1;
VDCL_totalbaupkgdesaddr2;
VDCL_totalbaupkgdesaddr3;
VDCL_totalbaupkgnum0;
VDCL_totalbaupkgnum1;
VDCL_totalbaupkgnum2;
VDCL_totalbaupkgnum3;
VDCL_v_iaq;        /*俯仰速率表决值                       */
VDCL_v_vdltwowsw;        /*左轮载开关                         */
VDCL_vpu_ccdl_status;        /*VPU数据CCDL有效状态                 */

/* declaration  end                  Don't remove this line */ 





/* 第0套方案数据 */

bau_pkg_element const FCRM_FTI1[206] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE },
{(word16 *)&piu_data_err                                               ,  32, BIT16_TYPE  },
{(word16 *)&piu_ram.svpc_err                                           ,  34, BIT16_TYPE  },
{(word16 *)&piu_ccdl_status                                            ,  36, BIT16_TYPE  },
{(word16 *)&piu_ram.hb_change                                          ,  38, BIT16_TYPE  },
{(word16 *)&ads_data_err                                               ,  40, BIT16_TYPE  },
{(word16 *)&ads_ram.svpc_err                                           ,  42, BIT16_TYPE  },
{(word16 *)&ads_ccdl_status                                            ,  44, BIT16_TYPE  },
{(word16 *)&ads_ram.hb_change                                          ,  46, BIT16_TYPE  },
{(word16 *)&ins_data_err                                               ,  48, BIT16_TYPE  },
{(word16 *)&ins_ram.svpc_err                                           ,  50, BIT16_TYPE  },
{(word16 *)&ins_ccdl_status                                            ,  52, BIT16_TYPE  },
{(word16 *)&ins_ram.hb_change                                          ,  54, BIT16_TYPE  },
{(word16 *)&acon_data_err                                              ,  56, BIT16_TYPE  },
{(word16 *)&acon_ram.svpc_err                                          ,  58, BIT16_TYPE  },
{(word16 *)&acon_ccdl_status                                           ,  60, BIT16_TYPE  },
{(word16 *)&acon_ram.hb_change                                         ,  62, BIT16_TYPE  },
{(word16 *)&etcl_data_err                                              ,  64, BIT16_TYPE  },
{(word16 *)&etcl_ram.svpc_err                                          ,  66, BIT16_TYPE  },
{(word16 *)&etcl_ccdl_status                                           ,  68, BIT16_TYPE  },
{(word16 *)&etcl_ram.hb_change                                         ,  70, BIT16_TYPE  },
{(word16 *)&etcr_data_err                                              ,  72, BIT16_TYPE  },
{(word16 *)&etcr_ram.svpc_err                                          ,  74, BIT16_TYPE  },
{(word16 *)&etcr_ccdl_status                                           ,  76, BIT16_TYPE  },
{(word16 *)&etcr_ram.hb_change                                         ,  78, BIT16_TYPE  },
{(word16 *)&isacf_data_err                                             ,  80, BIT16_TYPE  },
{(word16 *)&isacf_ram.svpc_err                                         ,  82, BIT16_TYPE  },
{(word16 *)&isacf_ccdl_status                                          ,  84, BIT16_TYPE  },
{(word16 *)&isacf_ram.hb_change                                        ,  86, BIT16_TYPE  },
{(word16 *)&isacb_data_err                                             ,  88, BIT16_TYPE  },
{(word16 *)&isacb_ram.svpc_err                                         ,  90, BIT16_TYPE  },
{(word16 *)&isacb_ccdl_status                                          ,  92, BIT16_TYPE  },
{(word16 *)&isacb_ram.hb_change                                        ,  94, BIT16_TYPE  },
{(word16 *)&vpu_data_err                                               ,  96, BIT16_TYPE  },
{(word16 *)&vpu_ram.svpc_err                                           ,  98, BIT16_TYPE  },
{(word16 *)&vpu_ccdl_status                                            , 100, BIT16_TYPE  },
{(word16 *)&vpu_ram.hb_change                                          , 102, BIT16_TYPE  },
{(word16 *)&icp2_fti                                                   , 104, BIT16_TYPE  },
{(word16 *)&dmp_a_fti                                                  , 106, BIT16_TYPE  },
{(word32 *)&spare32[1]                                                 , 108, WORD32_TYPE },
{(word16 *)&adp_ram.sensor_status                                      , 112, BIT16_TYPE  },
{(word16 *)&adp_ram.signal_status                                      , 114, BIT16_TYPE  },
{(int16 *)&v_iadp                                                      , 116, INT16_TYPE  },
{(word16 *)&adp_ram.vot_sup                                            , 118, WORD16_TYPE },
{(word16 *)&adp_ram.mon_sup                                            , 120, WORD16_TYPE },
{(word16 *)&adr_ram.sensor_status                                      , 122, BIT16_TYPE  },
{(word16 *)&adr_ram.signal_status                                      , 124, BIT16_TYPE  },
{(int16 *)&v_iadr                                                      , 126, INT16_TYPE  },
{(word16 *)&adr_ram.vot_sup                                            , 128, WORD16_TYPE },
{(word16 *)&adr_ram.mon_sup                                            , 130, WORD16_TYPE },
{(word16 *)&ady_ram.sensor_status                                      , 132, BIT16_TYPE  },
{(word16 *)&ady_ram.signal_status                                      , 134, BIT16_TYPE  },
{(int16 *)&v_iady                                                      , 136, INT16_TYPE  },
{(word16 *)&ady_ram.vot_sup                                            , 138, WORD16_TYPE },
{(word16 *)&ady_ram.mon_sup                                            , 140, WORD16_TYPE },
{(word16 *)&althrtl_ram.sensor_status                                  , 142, BIT16_TYPE  },
{(word16 *)&althrtl_ram.signal_status                                  , 144, BIT16_TYPE  },
{(int16 *)&v_ialthrtl                                                  , 146, INT16_TYPE  },
{(word16 *)&althrtl_ram.vot_sup                                        , 148, WORD16_TYPE },
{(word16 *)&althrtl_ram.mon_sup                                        , 150, WORD16_TYPE },
{(word16 *)&arthrtl_ram.sensor_status                                  , 152, BIT16_TYPE  },
{(word16 *)&arthrtl_ram.signal_status                                  , 154, BIT16_TYPE  },
{(int16 *)&v_iarthrtl                                                  , 156, INT16_TYPE  },
{(word16 *)&arthrtl_ram.vot_sup                                        , 158, WORD16_TYPE },
{(word16 *)&arthrtl_ram.mon_sup                                        , 160, WORD16_TYPE },
{(word16 *)&anz_ram.sensor_status                                      , 162, BIT16_TYPE  },
{(word16 *)&anz_ram.signal_status                                      , 164, BIT16_TYPE  },
{(int16 *)&v_ianz                                                      , 166, INT16_TYPE  },
{(word16 *)&anz_ram.vot_sup                                            , 168, WORD16_TYPE },
{(word16 *)&anz_ram.mon_sup                                            , 170, WORD16_TYPE },
{(word16 *)&any_ram.sensor_status                                      , 172, BIT16_TYPE  },
{(word16 *)&any_ram.signal_status                                      , 174, BIT16_TYPE  },
{(int16 *)&v_iany                                                      , 176, INT16_TYPE  },
{(word16 *)&any_ram.vot_sup                                            , 178, WORD16_TYPE },
{(word16 *)&any_ram.mon_sup                                            , 180, WORD16_TYPE },
{(word16 *)&anx_ram.sensor_status                                      , 182, BIT16_TYPE  },
{(word16 *)&anx_ram.signal_status                                      , 184, BIT16_TYPE  },
{(int16 *)&v_ianx                                                      , 186, INT16_TYPE  },
{(word16 *)&anx_ram.vot_sup                                            , 188, WORD16_TYPE },
{(word16 *)&anx_ram.mon_sup                                            , 190, WORD16_TYPE },
{(word16 *)&ap_ram.sensor_status                                       , 192, BIT16_TYPE  },
{(word16 *)&ap_ram.signal_status                                       , 194, BIT16_TYPE  },
{(int16 *)&v_iap                                                       , 196, INT16_TYPE  },
{(word16 *)&ap_ram.vot_sup                                             , 198, WORD16_TYPE },
{(word16 *)&ap_ram.mon_sup                                             , 200, WORD16_TYPE },
{(word16 *)&aq_ram.sensor_status                                       , 202, BIT16_TYPE  },
{(word16 *)&aq_ram.signal_status                                       , 204, BIT16_TYPE  },
{(int16 *)&v_iaq                                                       , 206, INT16_TYPE  },
{(word16 *)&aq_ram.vot_sup                                             , 208, WORD16_TYPE },
{(word16 *)&aq_ram.mon_sup                                             , 210, WORD16_TYPE },
{(word16 *)&ar_ram.sensor_status                                       , 212, BIT16_TYPE  },
{(word16 *)&ar_ram.signal_status                                       , 214, BIT16_TYPE  },
{(int16 *)&v_iar                                                       , 216, INT16_TYPE  },
{(word16 *)&ar_ram.vot_sup                                             , 218, WORD16_TYPE },
{(word16 *)&ar_ram.mon_sup                                             , 220, WORD16_TYPE },
{(word16 *)&spare32[2]                                                 , 222, WORD16_TYPE },
{(word32 *)&spare32[3]                                                 , 224, WORD32_TYPE },
{(word32 *)&spare32[4]                                                 , 228, WORD32_TYPE },
{(word16 *)&aloesp_ram.sensor_status                                   , 232, BIT16_TYPE  },
{(word16 *)&aloesp_ram.signal_status                                   , 234, BIT16_TYPE  },
{(int16 *)&v_ialoesp                                                   , 236, INT16_TYPE  },
{(word16 *)&aliesp_ram.sensor_status                                   , 238, BIT16_TYPE  },
{(word16 *)&aliesp_ram.signal_status                                   , 240, BIT16_TYPE  },
{(int16 *)&v_ialiesp                                                   , 242, INT16_TYPE  },
{(word16 *)&aroesp_ram.valid_signals                                   , 244, WORD16_TYPE },
{(word16 *)&aroesp_ram.signal_status                                   , 246, BIT16_TYPE  },
{(int16 *)&v_iaroesp                                                   , 248, INT16_TYPE  },
{(word16 *)&ariesp_ram.sensor_status                                   , 250, BIT16_TYPE  },
{(word16 *)&ariesp_ram.signal_status                                   , 252, BIT16_TYPE  },
{(int16 *)&v_iariesp                                                   , 254, INT16_TYPE  },
{(word16 *)&awspin_ram.sensor_status                                   , 256, BIT16_TYPE  },
{(word16 *)&awspin_ram.signal_status                                   , 258, BIT16_TYPE  },
{(int16 *)&v_iawspin                                                   , 260, INT16_TYPE  },
{(word16 *)&awspin_ram.vot_sup                                         , 262, WORD16_TYPE },
{(word16 *)&awspin_ram.mon_sup                                         , 264, WORD16_TYPE },
{(int16 *)&detulcse_ram.voted_ch[0]                                    , 266, INT16_TYPE  },
{(int16 *)&detulmon_ram.voted_ch[0]                                    , 268, INT16_TYPE  },
{(int16 *)&detulcse_ram.voted_ch[1]                                    , 270, INT16_TYPE  },
{(int16 *)&detulmon_ram.voted_ch[1]                                    , 272, INT16_TYPE  },
{(int16 *)&detulcse_ram.voted_ch[2]                                    , 274, INT16_TYPE  },
{(int16 *)&detulmon_ram.voted_ch[2]                                    , 276, INT16_TYPE  },
{(int16 *)&detulcse_ram.voted_ch[3]                                    , 278, INT16_TYPE  },
{(int16 *)&detulmon_ram.voted_ch[3]                                    , 280, INT16_TYPE  },
{(int16 *)&detulclut_ram.voted_ch[0]                                   , 282, INT16_TYPE  },
{(int16 *)&detulclut_ram.voted_ch[1]                                   , 284, INT16_TYPE  },
{(int16 *)&detulclut_ram.voted_ch[2]                                   , 286, INT16_TYPE  },
{(int16 *)&detulclut_ram.voted_ch[3]                                   , 288, INT16_TYPE  },
{(int16 *)&detuem_ram.voted_ch[0]                                      , 290, INT16_TYPE  },
{(int16 *)&detuem_ram.voted_ch[1]                                      , 292, INT16_TYPE  },
{(int16 *)&detclchv_ram.voted_ch[0]                                    , 294, INT16_TYPE  },
{(int16 *)&detclchv_ram.voted_ch[1]                                    , 296, INT16_TYPE  },
{(int16 *)&detclchv_ram.voted_ch[2]                                    , 298, INT16_TYPE  },
{(int16 *)&detclchv_ram.voted_ch[3]                                    , 300, INT16_TYPE  },
{(int16 *)&detclbusv_ram.voted_ch[0]                                   , 302, INT16_TYPE  },
{(int16 *)&detclbusv_ram.voted_ch[1]                                   , 304, INT16_TYPE  },
{(int16 *)&detclbusv_ram.voted_ch[2]                                   , 306, INT16_TYPE  },
{(int16 *)&detclbusv_ram.voted_ch[3]                                   , 308, INT16_TYPE  },
{(int16 *)&deturmon_ram.voted_ch[0]                                    , 310, INT16_TYPE  },
{(int16 *)&deturcse_ram.voted_ch[0]                                    , 312, INT16_TYPE  },
{(int16 *)&deturmon_ram.voted_ch[1]                                    , 314, INT16_TYPE  },
{(int16 *)&deturcse_ram.voted_ch[1]                                    , 316, INT16_TYPE  },
{(int16 *)&deturmon_ram.voted_ch[2]                                    , 318, INT16_TYPE  },
{(int16 *)&deturcse_ram.voted_ch[2]                                    , 320, INT16_TYPE  },
{(int16 *)&deturmon_ram.voted_ch[3]                                    , 322, INT16_TYPE  },
{(int16 *)&deturcse_ram.voted_ch[3]                                    , 324, INT16_TYPE  },
{(int16 *)&deturclut_ram.voted_ch[1]                                   , 326, INT16_TYPE  },
{(int16 *)&deturclut_ram.voted_ch[0]                                   , 328, INT16_TYPE  },
{(int16 *)&deturclut_ram.voted_ch[3]                                   , 330, INT16_TYPE  },
{(int16 *)&deturclut_ram.voted_ch[2]                                   , 332, INT16_TYPE  },
{(int16 *)&detuem_ram.voted_ch[3]                                      , 334, INT16_TYPE  },
{(int16 *)&detuem_ram.voted_ch[2]                                      , 336, INT16_TYPE  },
{(int16 *)&detcrchv_ram.voted_ch[1]                                    , 338, INT16_TYPE  },
{(int16 *)&detcrchv_ram.voted_ch[0]                                    , 340, INT16_TYPE  },
{(int16 *)&detcrchv_ram.voted_ch[3]                                    , 342, INT16_TYPE  },
{(int16 *)&detcrchv_ram.voted_ch[2]                                    , 344, INT16_TYPE  },
{(int16 *)&detcrbusv_ram.voted_ch[0]                                   , 346, INT16_TYPE  },
{(int16 *)&detcrbusv_ram.voted_ch[1]                                   , 348, INT16_TYPE  },
{(int16 *)&detcrbusv_ram.voted_ch[2]                                   , 350, INT16_TYPE  },
{(int16 *)&detcrbusv_ram.voted_ch[3]                                   , 352, INT16_TYPE  },
{(int16 *)&detulmon_ram.signal_status_ch[1]                            , 354, INT16_TYPE  },
{(int16 *)&detulcse_ram.signal_status_ch[0]                            , 356, INT16_TYPE  },
{(int16 *)&detulcse_ram.signal_status_ch[3]                            , 358, INT16_TYPE  },
{(int16 *)&detulmon_ram.signal_status_ch[2]                            , 360, INT16_TYPE  },
{(int16 *)&detulclut_ram.signal_status_ch[2]                           , 362, INT16_TYPE  },
{(int16 *)&detulclut_ram.signal_status_ch[1]                           , 364, INT16_TYPE  },
{(int16 *)&detuem_ram.signal_status_ch[1]                              , 366, INT16_TYPE  },
{(int16 *)&detuem_ram.signal_status_ch[0]                              , 368, INT16_TYPE  },
{(int16 *)&detclchv_ram.signal_status_ch[0]                            , 370, INT16_TYPE  },
{(int16 *)&detclbusv_ram.signal_status_ch[3]                           , 372, INT16_TYPE  },
{(int16 *)&deturmon_ram.signal_status_ch[0]                            , 374, INT16_TYPE  },
{(int16 *)&deturcse_ram.signal_status_ch[1]                            , 376, INT16_TYPE  },
{(int16 *)&deturcse_ram.signal_status_ch[2]                            , 378, INT16_TYPE  },
{(int16 *)&deturmon_ram.signal_status_ch[2]                            , 380, INT16_TYPE  },
{(int16 *)&deturclut_ram.signal_status_ch[2]                           , 382, INT16_TYPE  },
{(int16 *)&deturclut_ram.signal_status_ch[0]                           , 384, INT16_TYPE  },
{(int16 *)&detuem_ram.signal_status_ch[3]                              , 386, INT16_TYPE  },
{(int16 *)&detuem_ram.signal_status_ch[2]                              , 388, INT16_TYPE  },
{(int16 *)&detcrchv_ram.signal_status_ch[2]                            , 390, INT16_TYPE  },
{(int16 *)&detcrbusv_ram.signal_status_ch[0]                           , 392, INT16_TYPE  },
{(word16 *)&catcsftsw_ram.req_val                                      , 394, WORD16_TYPE },
{(word16 *)&configsftsw_ram.req_val                                    , 396, WORD16_TYPE },
{(word16 *)&hydcmdsftsw_ram.req_val                                    , 398, WORD16_TYPE },
{(word16 *)&trimclrsftsw_ram.req_val                                   , 400, WORD16_TYPE },
{(word16 *)&v_trimclrsftsw_sta                                         , 402, WORD16_TYPE },
{(word16 *)&ftastimsftsw_ram.req_val                                   , 404, WORD16_TYPE },
{(word16 *)&clselsftsw_ram.req_val                                     , 406, WORD16_TYPE },
{(word16 *)&fta_fcs_ft_sta                                             , 408, WORD16_TYPE },
{(word16 *)&fta_stimmod_inprogress                                     , 410, WORD16_TYPE },
{(word16 *)&ft_sys_stat_fail                                           , 412, WORD16_TYPE },
{(word16 *)&io_hyd_temp_vld                                            , 414, WORD16_TYPE },
{(word16 *)&io_lhyd_temp1                                              , 416, WORD16_TYPE },
{(word16 *)&io_lhyd_temp2                                              , 418, WORD16_TYPE },
{(word16 *)&io_rhyd_temp1                                              , 420, WORD16_TYPE },
{(word16 *)&io_rhyd_temp2                                              , 422, WORD16_TYPE },
{(word16 *)&lhyd_temp_avg                                              , 424, WORD16_TYPE },
{(word16 *)&rhyd_temp_avg                                              , 426, WORD16_TYPE },
{(word32 *)&spare32[22]                                                , 440, WORD32_TYPE },
{(word32 *)&spare32[23]                                                , 444, WORD32_TYPE },
{(word32 *)&spare32[24]                                                , 448, WORD32_TYPE },
{(int32 *)&io_acpu1temp                                                , 452, INT32_TYPE  },
{(int32 *)&io_acpu2temp                                                , 456, INT32_TYPE  },
{(int32 *)&io_amv1temp                                                 , 460, INT32_TYPE  },
{(int32 *)&io_amv2temp                                                 , 464, INT32_TYPE  },
{(int32 *)&io_acsbiutemp                                               , 468, INT32_TYPE  }};

bau_pkg_element const FCRM_FTI2[218] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE },
{(int16 *)&ins_acosteta[0]                                             ,  32, INT16_TYPE  },
{(int16 *)&ins_acosteta[1]                                             ,  34, INT16_TYPE  },
{(int16 *)&v_icosteta                                                  ,  36, INT16_TYPE  },
{(word16 *)&acosteta_ram.mon_sup                                       ,  38, WORD16_TYPE },
{(word16 *)&acosteta_ram.sig_status                                    ,  40, BIT16_TYPE  },
{(int16 *)&ins_asinphi[0]                                              ,  42, INT16_TYPE  },
{(int16 *)&ins_asinphi[1]                                              ,  44, INT16_TYPE  },
{(int16 *)&v_isinphi                                                   ,  46, INT16_TYPE  },
{(word16 *)&asinphi_ram.mon_sup                                        ,  48, WORD16_TYPE },
{(word16 *)&asinphi_ram.sig_status                                     ,  50, BIT16_TYPE  },
{(int16 *)&ins_acosphi[0]                                              ,  52, INT16_TYPE  },
{(int16 *)&ins_acosphi[1]                                              ,  54, INT16_TYPE  },
{(int16 *)&v_icosphi                                                   ,  56, INT16_TYPE  },
{(word16 *)&acosphi_ram.mon_sup                                        ,  58, WORD16_TYPE },
{(word16 *)&acosphi_ram.sig_status                                     ,  60, BIT16_TYPE  },
{(int16 *)&ins_agndspd[0]                                              ,  62, INT16_TYPE  },
{(int16 *)&ins_agndspd[1]                                              ,  64, INT16_TYPE  },
{(int16 *)&v_igndspd                                                   ,  66, INT16_TYPE  },
{(word16 *)&agndspd_ram.mon_sup                                        ,  68, WORD16_TYPE },
{(word16 *)&agndspd_ram.sig_status                                     ,  70, BIT16_TYPE  },
{(int16 *)&ins_agndtrka[0]                                             ,  72, INT16_TYPE  },
{(int16 *)&ins_agndtrka[1]                                             ,  74, INT16_TYPE  },
{(int16 *)&v_igndtrka                                                  ,  76, INT16_TYPE  },
{(word16 *)&agndtrka_ram.mon_sup                                       ,  78, WORD16_TYPE },
{(word16 *)&agndtrka_ram.sig_status                                    ,  80, BIT16_TYPE  },
{(int16 *)&ins_atotvel[0]                                              ,  82, INT16_TYPE  },
{(int16 *)&ins_atotvel[1]                                              ,  84, INT16_TYPE  },
{(int16 *)&v_itotvel                                                   ,  86, INT16_TYPE  },
{(word16 *)&atotvel_ram.mon_sup                                        ,  88, WORD16_TYPE },
{(word16 *)&atotvel_ram.sig_status                                     ,  90, BIT16_TYPE  },
{(int16 *)&ins_agama[0]                                                ,  92, INT16_TYPE  },
{(int16 *)&ins_agama[1]                                                ,  94, INT16_TYPE  },
{(int16 *)&v_igama                                                     ,  96, INT16_TYPE  },
{(word16 *)&agama_ram.mon_sup                                          ,  98, WORD16_TYPE },
{(word16 *)&agama_ram.sig_status                                       , 100, BIT16_TYPE  },
{(int16 *)&ins_ainsalt[0]                                              , 102, INT16_TYPE  },
{(int16 *)&ins_ainsalt[1]                                              , 104, INT16_TYPE  },
{(int16 *)&v_iinsalt                                                   , 106, INT16_TYPE  },
{(word16 *)&ainsalt_ram.mon_sup                                        , 108, WORD16_TYPE },
{(word16 *)&ainsalt_ram.sig_status                                     , 110, BIT16_TYPE  },
{(int16 *)&ins_aupvel[0]                                               , 112, INT16_TYPE  },
{(int16 *)&ins_aupvel[1]                                               , 114, INT16_TYPE  },
{(int16 *)&v_iupvel                                                    , 116, INT16_TYPE  },
{(word16 *)&aupvel_ram.mon_sup                                         , 118, WORD16_TYPE },
{(word16 *)&aupvel_ram.sig_status                                      , 120, BIT16_TYPE  },
{(int16 *)&ins_aphi[0]                                                 , 122, INT16_TYPE  },
{(int16 *)&ins_aphi[1]                                                 , 124, INT16_TYPE  },
{(int16 *)&v_iphi                                                      , 126, INT16_TYPE  },
{(word16 *)&aphi_ram.mon_sup                                           , 128, WORD16_TYPE },
{(word16 *)&aphi_ram.sig_status                                        , 130, BIT16_TYPE  },
{(int16 *)&ins_athdg[0]                                                , 132, INT16_TYPE  },
{(int16 *)&ins_athdg[1]                                                , 134, INT16_TYPE  },
{(int16 *)&v_ithdg                                                     , 136, INT16_TYPE  },
{(word16 *)&athdg_ram.mon_sup                                          , 138, WORD16_TYPE },
{(word16 *)&athdg_ram.sig_status                                       , 140, BIT16_TYPE  },
{(int16 *)&ins_atheta[0]                                               , 142, INT16_TYPE  },
{(int16 *)&ins_atheta[1]                                               , 144, INT16_TYPE  },
{(int16 *)&v_itheta                                                    , 146, INT16_TYPE  },
{(word16 *)&atheta_ram.mon_sup                                         , 148, WORD16_TYPE },
{(word16 *)&atheta_ram.sig_status                                      , 150, BIT16_TYPE  },
{(int16 *)&ins_ainsuvel[0]                                             , 152, INT16_TYPE  },
{(int16 *)&ins_ainsuvel[1]                                             , 154, INT16_TYPE  },
{(int16 *)&v_iinsuvel                                                  , 156, INT16_TYPE  },
{(word16 *)&ainsuvel_ram.mon_sup                                       , 158, WORD16_TYPE },
{(word16 *)&ainsuvel_ram.sig_status                                    , 160, BIT16_TYPE  },
{(int16 *)&ins_ainsgnsalt[0]                                           , 162, INT16_TYPE  },
{(int16 *)&ins_ainsgnsalt[1]                                           , 164, INT16_TYPE  },
{(int16 *)&v_iinsgnsalt                                                , 166, INT16_TYPE  },
{(word16 *)&ainsgnsalt_ram.mon_sup                                     , 168, WORD16_TYPE },
{(word16 *)&ainsgnsalt_ram.sig_status                                  , 170, BIT16_TYPE  },
{(int16 *)&ins_ainsaq[0]                                               , 172, INT16_TYPE  },
{(int16 *)&ins_ainsaq[1]                                               , 174, INT16_TYPE  },
{(int16 *)&v_iinsaq                                                    , 176, INT16_TYPE  },
{(word16 *)&ainsaq_ram.mon_sup                                         , 178, WORD16_TYPE },
{(word16 *)&ainsaq_ram.sig_status                                      , 180, BIT16_TYPE  },
{(int16 *)&ins_ainsap[0]                                               , 182, INT16_TYPE  },
{(int16 *)&ins_ainsap[1]                                               , 184, INT16_TYPE  },
{(int16 *)&v_iinsap                                                    , 186, INT16_TYPE  },
{(word16 *)&ainsap_ram.mon_sup                                         , 188, WORD16_TYPE },
{(word16 *)&ainsap_ram.sig_status                                      , 190, BIT16_TYPE  },
{(int16 *)&ins_ainsar[0]                                               , 192, INT16_TYPE  },
{(int16 *)&ins_ainsar[1]                                               , 194, INT16_TYPE  },
{(int16 *)&v_iinsar                                                    , 196, INT16_TYPE  },
{(word16 *)&ainsar_ram.mon_sup                                         , 198, WORD16_TYPE },
{(word16 *)&ainsar_ram.sig_status                                      , 200, BIT16_TYPE  },
{(int16 *)&ins_ainsnz[0]                                               , 202, INT16_TYPE  },
{(int16 *)&ins_ainsnz[1]                                               , 204, INT16_TYPE  },
{(int16 *)&v_iinsnz                                                    , 206, INT16_TYPE  },
{(word16 *)&ainsnz_ram.sig_status                                      , 208, WORD16_TYPE },
{(int16 *)&ins_ainsny[0]                                               , 210, INT16_TYPE  },
{(int16 *)&ins_ainsny[1]                                               , 212, INT16_TYPE  },
{(int16 *)&v_iinsny                                                    , 214, INT16_TYPE  },
{(word16 *)&ainsny_ram.sig_status                                      , 216, WORD16_TYPE },
{(int16 *)&ins_ainsnx[0]                                               , 218, INT16_TYPE  },
{(int16 *)&ins_ainsnx[1]                                               , 220, INT16_TYPE  },
{(int16 *)&v_iinsnx                                                    , 222, INT16_TYPE  },
{(word16 *)&ainsnx_ram.sig_status                                      , 224, WORD16_TYPE },
{(word16 *)&spare16[1]                                                 , 226, WORD16_TYPE },
{(word16 *)&apt_ram.sensor_status                                      , 228, WORD16_TYPE },
{(word16 *)&aps_ram.sensor_status                                      , 230, WORD16_TYPE },
{(word16 *)&aoa_ram.sensor_status                                      , 232, WORD16_TYPE },
{(word16 *)&aos_ram.sensor_status                                      , 234, WORD16_TYPE },
{(word16 *)&ads_usim_heat                                              , 236, BIT16_TYPE  },
{(word16 *)&ads_heat_lshape                                            , 238, BIT16_TYPE  },
{(word16 *)&ads_heat_body                                              , 240, BIT16_TYPE  },
{(int16 *)&aos_rvr_cnt                                                 , 242, INT16_TYPE  },
{(int16 *)&low_qc_flg                                                  , 244, INT16_TYPE  },
{(int16 *)&aoa_rvr_cnt                                                 , 246, INT16_TYPE  },
{(int16 *)&v_idaoacho                                                  , 248, INT16_TYPE  },
{(int16 *)&hi_aoa_flg                                                  , 250, INT16_TYPE  },
{(int16 *)&ma_075_flg                                                  , 252, INT16_TYPE  },
{(int16 *)&ma_090_flg                                                  , 254, INT16_TYPE  },
{(word16 *)&aoa_ram.signal_status                                      , 256, BIT16_TYPE  },
{(int16 *)&v_iaoa                                                      , 258, INT16_TYPE  },
{(int16 *)&aoa_ram.vot_sup                                             , 260, INT16_TYPE  },
{(int16 *)&aoa_ram.mon_sup                                             , 262, INT16_TYPE  },
{(word16 *)&aos_ram.signal_status                                      , 264, BIT16_TYPE  },
{(int16 *)&v_iaos                                                      , 266, INT16_TYPE  },
{(int16 *)&aos_ram.vot_sup                                             , 268, INT16_TYPE  },
{(int16 *)&aos_ram.mon_sup                                             , 270, INT16_TYPE  },
{(word16 *)&aps_ram.signal_status                                      , 272, BIT16_TYPE  },
{(int16 *)&v_iaps                                                      , 274, INT16_TYPE  },
{(int16 *)&aps_ram.vot_sup                                             , 276, INT16_TYPE  },
{(int16 *)&aps_ram.mon_sup                                             , 278, INT16_TYPE  },
{(word16 *)&avt_ram.signal_status                                      , 280, BIT16_TYPE  },
{(int16 *)&v_iavt                                                      , 282, INT16_TYPE  },
{(int16 *)&avt_ram.vot_sup                                             , 284, INT16_TYPE  },
{(int16 *)&avt_ram.mon_sup                                             , 286, INT16_TYPE  },
{(word16 *)&apt_ram.signal_status                                      , 288, BIT16_TYPE  },
{(int16 *)&v_iapt                                                      , 290, INT16_TYPE  },
{(int16 *)&apt_ram.vot_sup                                             , 292, INT16_TYPE  },
{(int16 *)&apt_ram.mon_sup                                             , 294, INT16_TYPE  },
{(int16 *)&ads_mpt_ava                                                 , 296, INT16_TYPE  },
{(int16 *)&ads_mps_ava                                                 , 298, INT16_TYPE  },
{(int16 *)&ads_maoa_ava                                                , 300, INT16_TYPE  },
{(int16 *)&ads_maos_ava                                                , 302, INT16_TYPE  },
{(int16 *)&ads_mvt_ava                                                 , 304, INT16_TYPE  },
{(int16 *)&v_ips_mea                                                   , 306, INT16_TYPE  },
{(int16 *)&v_ipt_mea                                                   , 308, INT16_TYPE  },
{(int16 *)&v_iaoa_mea                                                  , 310, INT16_TYPE  },
{(int16 *)&v_iaos_mea                                                  , 312, INT16_TYPE  },
{(int16 *)&v_ivt_mea                                                   , 314, INT16_TYPE  },
{(int16 *)&ads_mea_ilm_flr[1]                                          , 316, INT16_TYPE  },
{(int16 *)&ads_mea_ilm_flr[0]                                          , 318, INT16_TYPE  },
{(int16 *)&ads_mea_ilm_flr[2]                                          , 320, INT16_TYPE  },
{(int16 *)&ads_mea_ilm_flr[3]                                          , 322, INT16_TYPE  },
{(int16 *)&v_iaqc                                                      , 324, INT16_TYPE  },
{(word16 *)&wnd_stop_cmd                                               , 326, BIT16_TYPE  },
{(int16 *)&wnd_ps_ram.wnd_vld_sig                                      , 328, INT16_TYPE  },
{(word16 *)&wnd_ps_ram.wnd_sig_sts                                     , 330, BIT16_TYPE  },
{(int16 *)&wnd_pt_ram.wnd_vld_sig                                      , 332, INT16_TYPE  },
{(word16 *)&wnd_pt_ram.wnd_sig_sts                                     , 334, BIT16_TYPE  },
{(int16 *)&wnd_aoa_ram.wnd_vld_sig                                     , 336, INT16_TYPE  },
{(word16 *)&wnd_aoa_ram.wnd_sig_sts                                    , 338, BIT16_TYPE  },
{(word16 *)&est_ps_ram.est_sig_sts                                     , 340, BIT16_TYPE  },
{(int16 *)&est_ps_ram.est_sig_num                                      , 342, INT16_TYPE  },
{(int16 *)&est_ps_ram.est_mon_sts                                      , 344, INT16_TYPE  },
{(int16 *)&est_ps_ram.est_mon_num                                      , 346, INT16_TYPE  },
{(int16 *)&est_ps_ram.est_mon_sup                                      , 348, INT16_TYPE  },
{(int16 *)&est_ps_ram.est_vot_sup                                      , 350, INT16_TYPE  },
{(int16 *)&ads_eps_ava                                                 , 352, INT16_TYPE  },
{(int16 *)&v_ips_est                                                   , 354, INT16_TYPE  },
{(int16 *)&est_ps_ram.est_rvr_delay                                    , 356, INT16_TYPE  },
{(int16 *)&est_ps_ram.est_rvr_cnt                                      , 358, INT16_TYPE  },
{(word16 *)&est_pt_ram.est_sig_sts                                     , 360, BIT16_TYPE  },
{(int16 *)&est_pt_ram.est_sig_num                                      , 362, INT16_TYPE  },
{(int16 *)&est_pt_ram.est_mon_sts                                      , 364, INT16_TYPE  },
{(int16 *)&est_pt_ram.est_mon_num                                      , 366, INT16_TYPE  },
{(int16 *)&est_pt_ram.est_mon_sup                                      , 368, INT16_TYPE  },
{(int16 *)&est_pt_ram.est_vot_sup                                      , 370, INT16_TYPE  },
{(int16 *)&ads_ept_ava                                                 , 372, INT16_TYPE  },
{(int16 *)&v_ipt_est                                                   , 374, INT16_TYPE  },
{(int16 *)&est_pt_ram.est_rvr_delay                                    , 376, INT16_TYPE  },
{(int16 *)&est_pt_ram.est_rvr_cnt                                      , 378, INT16_TYPE  },
{(word16 *)&est_aoa_ram.est_sig_sts                                    , 380, BIT16_TYPE  },
{(int16 *)&est_aoa_ram.est_sig_num                                     , 382, INT16_TYPE  },
{(int16 *)&est_aoa_ram.est_mon_sts                                     , 384, INT16_TYPE  },
{(int16 *)&est_aoa_ram.est_mon_num                                     , 386, INT16_TYPE  },
{(int16 *)&est_aoa_ram.est_mon_sup                                     , 388, INT16_TYPE  },
{(int16 *)&est_aoa_ram.est_vot_sup                                     , 390, INT16_TYPE  },
{(int16 *)&ads_eaoa_ava                                                , 392, INT16_TYPE  },
{(int16 *)&v_iaoa_est                                                  , 394, INT16_TYPE  },
{(int16 *)&est_aoa_ram.est_rvr_delay                                   , 396, INT16_TYPE  },
{(int16 *)&est_aoa_ram.est_rvr_cnt                                     , 398, INT16_TYPE  },
{(word16 *)&est_aos_ram.est_sig_sts                                    , 400, BIT16_TYPE  },
{(int16 *)&est_aos_ram.est_sig_num                                     , 402, INT16_TYPE  },
{(int16 *)&est_aos_ram.est_mon_sts                                     , 404, INT16_TYPE  },
{(int16 *)&est_aos_ram.est_mon_num                                     , 406, INT16_TYPE  },
{(int16 *)&est_aos_ram.est_mon_sup                                     , 408, INT16_TYPE  },
{(int16 *)&est_aos_ram.est_vot_sup                                     , 410, INT16_TYPE  },
{(int16 *)&ads_eaos_ava                                                , 412, INT16_TYPE  },
{(int16 *)&v_iaos_est                                                  , 414, INT16_TYPE  },
{(int16 *)&est_aos_ram.est_rvr_delay                                   , 416, INT16_TYPE  },
{(int16 *)&est_aos_ram.est_rvr_cnt                                     , 418, INT16_TYPE  },
{(word32 *)&spare32[10]                                                , 420, WORD32_TYPE },
{(word32 *)&spare32[11]                                                , 424, WORD32_TYPE },
{(int16 *)&usim_ltengn21                                               , 428, INT16_TYPE  },
{(int16 *)&usim_ltengn22                                               , 430, INT16_TYPE  },
{(int16 *)&usim_rtengn21                                               , 432, INT16_TYPE  },
{(int16 *)&usim_rtengn22                                               , 434, INT16_TYPE  },
{(int16*)&v_iltengn2                                                   , 436, INT16_TYPE  },
{(int16*)&v_irtengn2                                                   , 438, INT16_TYPE  },
{(word16 *)&inh_wri_nvm                                                , 440, WORD16_TYPE },
{(word16 *)&spare32[14]                                                , 442, WORD16_TYPE },
{(word16 *)&axes_aq_ram.ms_vs                                          , 444, WORD16_TYPE },
{(word16 *)&axes_ap_ram.ms_vs                                          , 446, WORD16_TYPE },
{(word16 *)&axes_ar_ram.ms_vs                                          , 448, WORD16_TYPE },
{(word16 *)&axes_nz_ram.ms_vs                                          , 450, WORD16_TYPE },
{(word16 *)&axes_nx_ram.ms_vs                                          , 452, WORD16_TYPE },
{(word16 *)&spare32[17]                                                , 454, WORD16_TYPE },
{(word32 *)&spare32[18]                                                , 456, WORD32_TYPE },
{(word32 *)&spare32[19]                                                , 460, WORD32_TYPE },
{(word32 *)&spare32[20]                                                , 464, WORD32_TYPE },
{(word32 *)&spare32[21]                                                , 468, WORD32_TYPE },
{(word32 *)&spare32[22]                                                , 472, WORD32_TYPE }};

bau_pkg_element const FCRM_FTI3[220] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE },
{(word16 *)&dltwowsw_ram.signal_status                                 ,  32, BIT16_TYPE  },
{(int16 *)&v_vdltwowsw                                                 ,  34, INT16_TYPE  },
{(word16 *)&dltwowsw_ram.vot_sup                                       ,  36, WORD16_TYPE },
{(word16 *)&dltwowsw_ram.mon_sup                                       ,  38, WORD16_TYPE },
{(word16 *)&drtwowsw_ram.signal_status                                 ,  40, BIT16_TYPE  },
{(int16 *)&v_vdrtwowsw                                                 ,  42, INT16_TYPE  },
{(word16 *)&drtwowsw_ram.vot_sup                                       ,  44, WORD16_TYPE },
{(word16 *)&drtwowsw_ram.mon_sup                                       ,  46, WORD16_TYPE },
{(word16 *)&wow_vm_sup                                                 ,  48, WORD16_TYPE },
{(word16 *)&v_vdwowsw                                                  ,  50, WORD16_TYPE },
{(word16 *)&dfcsrstsw_ram.signal_status                                ,  52, BIT16_TYPE  },
{(int16 *)&v_vdfcsrstsw                                                ,  54, INT16_TYPE  },
{(word16 *)&dfcsrstsw_ram.vot_sup                                      ,  56, WORD16_TYPE },
{(word16 *)&dfcsrstsw_ram.mon_sup                                      ,  58, WORD16_TYPE },
{(word16 *)&drstreqsw_ram.signal_status                                ,  60, BIT16_TYPE  },
{(int16 *)&v_vdrstreqsw                                                ,  62, INT16_TYPE  },
{(word16 *)&drstreqsw_ram.vot_sup                                      ,  64, WORD16_TYPE },
{(word16 *)&drstreqsw_ram.mon_sup                                      ,  66, WORD16_TYPE },
{(word16 *)&dbitreqsw_ram.signal_status                                ,  68, BIT16_TYPE  },
{(int16 *)&v_vdbitreqsw                                                ,  70, INT16_TYPE  },
{(word16 *)&dbitreqsw_ram.vot_sup                                      ,  72, WORD16_TYPE },
{(word16 *)&dbitreqsw_ram.mon_sup                                      ,  74, WORD16_TYPE },
{(word16 *)&dbfccreq_ram.signal_status                                 ,  76, BIT16_TYPE  },
{(int16 *)&v_vdbfccreq                                                 ,  78, INT16_TYPE  },
{(word16 *)&dbfccreq_ram.vot_sup                                       ,  80, WORD16_TYPE },
{(word16 *)&dbfccreq_ram.mon_sup                                       ,  82, WORD16_TYPE },
{(word16 *)&dintrst_ram.signal_status                                  ,  84, BIT16_TYPE  },
{(int16 *)&v_vdintrst                                                  ,  86, INT16_TYPE  },
{(word16 *)&dintrst_ram.vot_sup                                        ,  88, WORD16_TYPE },
{(word16 *)&dintrst_ram.mon_sup                                        ,  90, WORD16_TYPE },
{(word16 *)&dacid3sw_ram.signal_status                                 ,  92, BIT16_TYPE  },
{(int16 *)&v_vdacid3sw                                                 ,  94, INT16_TYPE  },
{(word16 *)&dacid2sw_ram.signal_status                                 ,  96, BIT16_TYPE  },
{(int16 *)&v_vdacid2sw                                                 ,  98, INT16_TYPE  },
{(word16 *)&dfwowsw_ram.signal_status                                  , 100, BIT16_TYPE  },
{(int16 *)&v_vdfwowsw                                                  , 102, INT16_TYPE  },
{(word16 *)&dllhdsw_ram.signal_status                                  , 104, BIT16_TYPE  },
{(int16 *)&v_vdllhdsw                                                  , 106, INT16_TYPE  },
{(word16 *)&dllhd1sw_ram.signal_status                                 , 108, BIT16_TYPE  },
{(int16 *)&v_vdllhd1sw                                                 , 110, INT16_TYPE  },
{(word16 *)&dllhd2sw_ram.signal_status                                 , 112, BIT16_TYPE  },
{(int16 *)&v_vdllhd2sw                                                 , 114, INT16_TYPE  },
{(word16 *)&drlhdsw_ram.signal_status                                  , 116, BIT16_TYPE  },
{(int16 *)&v_vdrlhdsw                                                  , 118, INT16_TYPE  },
{(word16 *)&drlhd1sw_ram.signal_status                                 , 120, BIT16_TYPE  },
{(int16 *)&v_vdrlhd1sw                                                 , 122, INT16_TYPE  },
{(word16 *)&drlhd2sw_ram.signal_status                                 , 124, BIT16_TYPE  },
{(int16 *)&v_vdrlhd2sw                                                 , 126, INT16_TYPE  },
{(word16 *)&ddlsw_ram.signal_status                                    , 128, BIT16_TYPE  },
{(int16 *)&v_vddlsw                                                    , 130, INT16_TYPE  },
{(word16 *)&dftsw_ram.signal_status                                    , 132, BIT16_TYPE  },
{(int16 *)&v_vdftsw                                                    , 134, INT16_TYPE  },
{(word16 *)&dfcsfocsw_ram.signal_status                                , 136, BIT16_TYPE  },
{(int16 *)&v_vdfcsfocsw                                                , 138, INT16_TYPE  },
{(word16 *)&dprobesw_ram.signal_status                                 , 140, BIT16_TYPE  },
{(int16 *)&v_vdprobesw                                                 , 142, INT16_TYPE  },
{(word16 *)&dlghsw_ram.signal_status                                   , 144, BIT16_TYPE  },
{(int16 *)&v_vdlghsw                                                   , 146, INT16_TYPE  },
{(word16 *)&dfcscfmsw_ram.signal_status                                , 148, BIT16_TYPE  },
{(int16 *)&v_vdfcscfmsw                                                , 150, INT16_TYPE  },
{(word16 *)&dputrsw_ram.signal_status                                  , 152, BIT16_TYPE  },
{(int16 *)&v_vdputrsw                                                  , 154, INT16_TYPE  },
{(word16 *)&dpdtrsw_ram.signal_status                                  , 156, BIT16_TYPE  },
{(int16 *)&v_vdpdtrsw                                                  , 158, INT16_TYPE  },
{(word16 *)&drltrsw_ram.signal_status                                  , 160, BIT16_TYPE  },
{(int16 *)&v_vdrltrsw                                                  , 162, INT16_TYPE  },
{(word16 *)&drrtrsw_ram.signal_status                                  , 164, BIT16_TYPE  },
{(int16 *)&v_vdrrtrsw                                                  , 166, INT16_TYPE  },
{(word16 *)&dyltrsw_ram.signal_status                                  , 168, BIT16_TYPE  },
{(int16 *)&v_vdyltrsw                                                  , 170, INT16_TYPE  },
{(word16 *)&dyrtrsw_ram.signal_status                                  , 172, BIT16_TYPE  },
{(int16 *)&v_vdyrtrsw                                                  , 174, INT16_TYPE  },
{(word16 *)&dmodisen_ram.signal_status                                 , 176, BIT16_TYPE  },
{(int16 *)&v_vdmodisen                                                 , 178, INT16_TYPE  },
{(word16 *)&dalsw_ram.signal_status                                    , 180, BIT16_TYPE  },
{(int16 *)&v_vdalsw                                                    , 182, INT16_TYPE  },
{(word16 *)&dvsbext_ram.signal_status                                  , 184, BIT16_TYPE  },
{(int16 *)&v_vdvsbext                                                  , 186, INT16_TYPE  },
{(word16 *)&dvsbret_ram.signal_status                                  , 188, BIT16_TYPE  },
{(int16 *)&v_vdvsbret                                                  , 190, INT16_TYPE  },
{(word16 *)&dnwsgsw_ram.signal_status                                  , 192, BIT16_TYPE  },
{(int16 *)&v_vdnwsgsw                                                  , 194, INT16_TYPE  },
{(word16 *)&dacid1sw_ram.signal_status                                 , 196, BIT16_TYPE  },
{(int16 *)&v_vdacid1sw                                                 , 198, INT16_TYPE  },
{(int16 *)&droecson_ram.voted_ch[0]                                    , 200, INT16_TYPE  },
{(int16 *)&droecson_ram.voted_ch[1]                                    , 202, INT16_TYPE  },
{(int16 *)&droecson_ram.voted_ch[2]                                    , 204, INT16_TYPE  },
{(int16 *)&droecson_ram.voted_ch[3]                                    , 206, INT16_TYPE  },
{(int16 *)&driecson_ram.voted_ch[0]                                    , 208, INT16_TYPE  },
{(int16 *)&driecson_ram.voted_ch[1]                                    , 210, INT16_TYPE  },
{(int16 *)&driecson_ram.voted_ch[2]                                    , 212, INT16_TYPE  },
{(int16 *)&driecson_ram.voted_ch[3]                                    , 214, INT16_TYPE  },
{(int16 *)&dloecson_ram.voted_ch[0]                                    , 216, INT16_TYPE  },
{(int16 *)&dloecson_ram.voted_ch[1]                                    , 218, INT16_TYPE  },
{(int16 *)&dloecson_ram.voted_ch[2]                                    , 220, INT16_TYPE  },
{(int16 *)&dloecson_ram.voted_ch[3]                                    , 222, INT16_TYPE  },
{(int16 *)&dliecson_ram.voted_ch[0]                                    , 224, INT16_TYPE  },
{(int16 *)&dliecson_ram.voted_ch[1]                                    , 226, INT16_TYPE  },
{(int16 *)&dliecson_ram.voted_ch[2]                                    , 228, INT16_TYPE  },
{(int16 *)&dliecson_ram.voted_ch[3]                                    , 230, INT16_TYPE  },
{(int16 *)&drccson_ram.voted_ch[0]                                     , 232, INT16_TYPE  },
{(int16 *)&drccson_ram.voted_ch[1]                                     , 234, INT16_TYPE  },
{(int16 *)&drccson_ram.voted_ch[2]                                     , 236, INT16_TYPE  },
{(int16 *)&drccson_ram.voted_ch[3]                                     , 238, INT16_TYPE  },
{(int16 *)&dlccson_ram.voted_ch[0]                                     , 240, INT16_TYPE  },
{(int16 *)&dlccson_ram.voted_ch[1]                                     , 242, INT16_TYPE  },
{(int16 *)&dlccson_ram.voted_ch[2]                                     , 244, INT16_TYPE  },
{(int16 *)&dlccson_ram.voted_ch[3]                                     , 246, INT16_TYPE  },
{(int16 *)&dlrudcson_ram.voted_ch[0]                                   , 248, INT16_TYPE  },
{(int16 *)&dlrudcson_ram.voted_ch[1]                                   , 250, INT16_TYPE  },
{(int16 *)&dlrudcson_ram.voted_ch[2]                                   , 252, INT16_TYPE  },
{(int16 *)&dlrudcson_ram.voted_ch[3]                                   , 254, INT16_TYPE  },
{(int16 *)&drrudcson_ram.voted_ch[0]                                   , 256, INT16_TYPE  },
{(int16 *)&drrudcson_ram.voted_ch[1]                                   , 258, INT16_TYPE  },
{(int16 *)&drrudcson_ram.voted_ch[2]                                   , 260, INT16_TYPE  },
{(int16 *)&drrudcson_ram.voted_ch[3]                                   , 262, INT16_TYPE  },
{(int16 *)&dlcsys1v_ram.voted_ch[0]                                    , 264, INT16_TYPE  },
{(int16 *)&dlcsys1v_ram.voted_ch[1]                                    , 266, INT16_TYPE  },
{(int16 *)&dlcsys1v_ram.voted_ch[2]                                    , 268, INT16_TYPE  },
{(int16 *)&dlcsys1v_ram.voted_ch[3]                                    , 270, INT16_TYPE  },
{(int16 *)&dlcsys2v_ram.voted_ch[0]                                    , 272, INT16_TYPE  },
{(int16 *)&dlcsys2v_ram.voted_ch[1]                                    , 274, INT16_TYPE  },
{(int16 *)&dlcsys2v_ram.voted_ch[2]                                    , 276, INT16_TYPE  },
{(int16 *)&dlcsys2v_ram.voted_ch[3]                                    , 278, INT16_TYPE  },
{(int16 *)&drcsys1v_ram.voted_ch[0]                                    , 280, INT16_TYPE  },
{(int16 *)&drcsys1v_ram.voted_ch[1]                                    , 282, INT16_TYPE  },
{(int16 *)&drcsys1v_ram.voted_ch[2]                                    , 284, INT16_TYPE  },
{(int16 *)&drcsys1v_ram.voted_ch[3]                                    , 286, INT16_TYPE  },
{(int16 *)&drcsys2v_ram.voted_ch[0]                                    , 288, INT16_TYPE  },
{(int16 *)&drcsys2v_ram.voted_ch[1]                                    , 290, INT16_TYPE  },
{(int16 *)&drcsys2v_ram.voted_ch[2]                                    , 292, INT16_TYPE  },
{(int16 *)&drcsys2v_ram.voted_ch[3]                                    , 294, INT16_TYPE  },
{(int16 *)&dliesys1v_ram.voted_ch[0]                                   , 296, INT16_TYPE  },
{(int16 *)&dliesys1v_ram.voted_ch[1]                                   , 298, INT16_TYPE  },
{(int16 *)&dliesys1v_ram.voted_ch[2]                                   , 300, INT16_TYPE  },
{(int16 *)&dliesys1v_ram.voted_ch[3]                                   , 302, INT16_TYPE  },
{(int16 *)&dliesys2v_ram.voted_ch[0]                                   , 304, INT16_TYPE  },
{(int16 *)&dliesys2v_ram.voted_ch[1]                                   , 306, INT16_TYPE  },
{(int16 *)&dliesys2v_ram.voted_ch[2]                                   , 308, INT16_TYPE  },
{(int16 *)&dliesys2v_ram.voted_ch[3]                                   , 310, INT16_TYPE  },
{(int16 *)&dloesys1v_ram.voted_ch[0]                                   , 312, INT16_TYPE  },
{(int16 *)&dloesys1v_ram.voted_ch[1]                                   , 314, INT16_TYPE  },
{(int16 *)&dloesys1v_ram.voted_ch[2]                                   , 316, INT16_TYPE  },
{(int16 *)&dloesys1v_ram.voted_ch[3]                                   , 318, INT16_TYPE  },
{(int16 *)&dloesys2v_ram.voted_ch[0]                                   , 320, INT16_TYPE  },
{(int16 *)&dloesys2v_ram.voted_ch[1]                                   , 322, INT16_TYPE  },
{(int16 *)&dloesys2v_ram.voted_ch[2]                                   , 324, INT16_TYPE  },
{(int16 *)&dloesys2v_ram.voted_ch[3]                                   , 326, INT16_TYPE  },
{(int16 *)&driesys1v_ram.voted_ch[0]                                   , 328, INT16_TYPE  },
{(int16 *)&driesys1v_ram.voted_ch[1]                                   , 330, INT16_TYPE  },
{(int16 *)&driesys1v_ram.voted_ch[2]                                   , 332, INT16_TYPE  },
{(int16 *)&driesys1v_ram.voted_ch[3]                                   , 334, INT16_TYPE  },
{(int16 *)&driesys2v_ram.voted_ch[0]                                   , 336, INT16_TYPE  },
{(int16 *)&driesys2v_ram.voted_ch[1]                                   , 338, INT16_TYPE  },
{(int16 *)&driesys2v_ram.voted_ch[2]                                   , 340, INT16_TYPE  },
{(int16 *)&driesys2v_ram.voted_ch[3]                                   , 342, INT16_TYPE  },
{(int16 *)&droesys1v_ram.voted_ch[0]                                   , 344, INT16_TYPE  },
{(int16 *)&droesys1v_ram.voted_ch[1]                                   , 346, INT16_TYPE  },
{(int16 *)&droesys1v_ram.voted_ch[2]                                   , 348, INT16_TYPE  },
{(int16 *)&droesys1v_ram.voted_ch[3]                                   , 350, INT16_TYPE  },
{(int16 *)&droesys2v_ram.voted_ch[0]                                   , 352, INT16_TYPE  },
{(int16 *)&droesys2v_ram.voted_ch[1]                                   , 354, INT16_TYPE  },
{(int16 *)&droesys2v_ram.voted_ch[2]                                   , 356, INT16_TYPE  },
{(int16 *)&droesys2v_ram.voted_ch[3]                                   , 358, INT16_TYPE  },
{(int16 *)&dlrudsys1v_ram.voted_ch[0]                                  , 360, INT16_TYPE  },
{(int16 *)&dlrudsys1v_ram.voted_ch[1]                                  , 362, INT16_TYPE  },
{(int16 *)&dlrudsys1v_ram.voted_ch[2]                                  , 364, INT16_TYPE  },
{(int16 *)&dlrudsys1v_ram.voted_ch[3]                                  , 366, INT16_TYPE  },
{(int16 *)&dlrudsys2v_ram.voted_ch[0]                                  , 368, INT16_TYPE  },
{(int16 *)&dlrudsys2v_ram.voted_ch[1]                                  , 370, INT16_TYPE  },
{(int16 *)&dlrudsys2v_ram.voted_ch[2]                                  , 372, INT16_TYPE  },
{(int16 *)&dlrudsys2v_ram.voted_ch[3]                                  , 374, INT16_TYPE  },
{(int16 *)&drrudsys1v_ram.voted_ch[0]                                  , 376, INT16_TYPE  },
{(int16 *)&drrudsys1v_ram.voted_ch[1]                                  , 378, INT16_TYPE  },
{(int16 *)&drrudsys1v_ram.voted_ch[2]                                  , 380, INT16_TYPE  },
{(int16 *)&drrudsys1v_ram.voted_ch[3]                                  , 382, INT16_TYPE  },
{(int16 *)&drrudsys2v_ram.voted_ch[0]                                  , 384, INT16_TYPE  },
{(int16 *)&drrudsys2v_ram.voted_ch[1]                                  , 386, INT16_TYPE  },
{(int16 *)&drrudsys2v_ram.voted_ch[2]                                  , 388, INT16_TYPE  },
{(int16 *)&drrudsys2v_ram.voted_ch[3]                                  , 390, INT16_TYPE  },
{(int16 *)&disacfchv_ram.voted_ch[0]                                   , 392, INT16_TYPE  },
{(int16 *)&disacfchv_ram.voted_ch[1]                                   , 394, INT16_TYPE  },
{(int16 *)&disacfchv_ram.voted_ch[2]                                   , 396, INT16_TYPE  },
{(int16 *)&disacfchv_ram.voted_ch[3]                                   , 398, INT16_TYPE  },
{(int16 *)&disacbchv_ram.voted_ch[0]                                   , 400, INT16_TYPE  },
{(int16 *)&disacbchv_ram.voted_ch[1]                                   , 402, INT16_TYPE  },
{(int16 *)&disacbchv_ram.voted_ch[2]                                   , 404, INT16_TYPE  },
{(int16 *)&disacbchv_ram.voted_ch[3]                                   , 406, INT16_TYPE  },
{(int16 *)&disacfbusv_ram.voted_ch[0]                                  , 408, INT16_TYPE  },
{(int16 *)&disacfbusv_ram.voted_ch[1]                                  , 410, INT16_TYPE  },
{(int16 *)&disacfbusv_ram.voted_ch[2]                                  , 412, INT16_TYPE  },
{(int16 *)&disacfbusv_ram.voted_ch[3]                                  , 414, INT16_TYPE  },
{(int16 *)&disacbbusv_ram.voted_ch[0]                                  , 416, INT16_TYPE  },
{(int16 *)&disacbbusv_ram.voted_ch[1]                                  , 418, INT16_TYPE  },
{(int16 *)&disacbbusv_ram.voted_ch[2]                                  , 420, INT16_TYPE  },
{(int16 *)&disacbbusv_ram.voted_ch[3]                                  , 422, INT16_TYPE  },
{(word16 *)&dlccson_ram.signal_status_ch[0]                            , 424, BIT16_TYPE  },
{(word16 *)&drccson_ram.signal_status_ch[2]                            , 426, BIT16_TYPE  },
{(word16 *)&dliecson_ram.signal_status_ch[1]                           , 428, BIT16_TYPE  },
{(word16 *)&dloecson_ram.signal_status_ch[2]                           , 430, BIT16_TYPE  },
{(word16 *)&driecson_ram.signal_status_ch[0]                           , 432, BIT16_TYPE  },
{(word16 *)&droecson_ram.signal_status_ch[3]                           , 434, BIT16_TYPE  },
{(word16 *)&dlrudcson_ram.signal_status_ch[0]                          , 436, BIT16_TYPE  },
{(word16 *)&drrudcson_ram.signal_status_ch[1]                          , 438, BIT16_TYPE  },
{(word16 *)&dlcsys1v_ram.signal_status_ch[0]                           , 440, BIT16_TYPE  },
{(word16 *)&drcsys2v_ram.signal_status_ch[1]                           , 442, BIT16_TYPE  },
{(word16 *)&dliesys1v_ram.signal_status_ch[2]                          , 444, BIT16_TYPE  },
{(word16 *)&driesys2v_ram.signal_status_ch[3]                          , 446, BIT16_TYPE  },
{(word16 *)&dlrudsys1v_ram.signal_status_ch[0]                         , 448, BIT16_TYPE  },
{(word16 *)&drrudsys2v_ram.signal_status_ch[2]                         , 450, BIT16_TYPE  },
{(word16 *)&disacfchv_ram.signal_status_ch[0]                          , 452, BIT16_TYPE  },
{(word16 *)&disacbchv_ram.signal_status_ch[1]                          , 454, BIT16_TYPE  },
{(word16 *)&disacfbusv_ram.signal_status_ch[2]                         , 456, BIT16_TYPE  },
{(word16 *)&disacbbusv_ram.signal_status_ch[3]                         , 458, BIT16_TYPE  },
{(word32 *)&io_acid_valid                                              , 460, BIT32_TYPE  },
{(word32 *)&spare32[5]                                                 , 464, WORD32_TYPE },
{(word32 *)&spare32[6]                                                 , 468, WORD32_TYPE }};

bau_pkg_element const FCRM_FTI4[148] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE },
{(word16 *)&susd_air_gnd                                               ,  32, WORD16_TYPE },
{(word16 *)&rcnf_scmbit                                                ,  34, WORD16_TYPE },
{(word16 *)&ch_health                                                  ,  36, BIT16_TYPE  },
{(word16 *)&self_ccdl_status                                           ,  38, BIT16_TYPE  },
{(word16 *)&sim_ccdl_status                                            ,  40, BIT16_TYPE  },
{(word16 *)&usim5_ccdl_status                                          ,  42, BIT16_TYPE  },
{(word16 *)&spare32[0]                                                 ,  44, WORD16_TYPE },
{(word16 *)&ch_sw_status                                               ,  46, BIT16_TYPE  },
{(word16 *)&ch_hw_valid                                                ,  48, BIT16_TYPE  },
{(word16 *)&sync_status                                                ,  50, BIT16_TYPE  },
{(int16 *)&out_cmd_lst[0]                                              ,  52, INT16_TYPE  },
{(int16 *)&out_cmd_lst[1]                                              ,  54, INT16_TYPE  },
{(int16 *)&out_cmd_lst[2]                                              ,  56, INT16_TYPE  },
{(int16 *)&out_cmd_lst[3]                                              ,  58, INT16_TYPE  },
{(int16 *)&out_cmd_lst[4]                                              ,  60, INT16_TYPE  },
{(int16 *)&out_cmd_lst[5]                                              ,  62, INT16_TYPE  },
{(int16 *)&out_cmd_lst[6]                                              ,  64, INT16_TYPE  },
{(int16 *)&out_cmd_lst[7]                                              ,  66, INT16_TYPE  },
{(int16 *)&out_cmd_lst[8]                                              ,  68, INT16_TYPE  },
{(int16 *)&out_cmd_lst[9]                                              ,  70, INT16_TYPE  },
{(word16 *)&mo_ocm_stat                                                ,  72, BIT16_TYPE  },
{(word16 *)&spare32[1]                                                 ,  74, WORD16_TYPE },
{(word32 *)&mo_cl_rcnf                                                 ,  76, BIT32_TYPE  },
{(word32 *)&mo_cl_rcf2                                                 ,  80, BIT32_TYPE  },
{(word16 *)&acon_scsflg                                                ,  84, WORD16_TYPE },
{(word16 *)&isacf_scsflg                                               ,  86, WORD16_TYPE },
{(word16 *)&spare32[2]                                                 ,  88, WORD16_TYPE },
{(word16 *)&piu_scsflg                                                 ,  90, WORD16_TYPE },
{(word16 *)&ads_scsflg                                                 ,  92, WORD16_TYPE },
{(word16 *)&spare32[3]                                                 ,  94, WORD16_TYPE },
{(word32 *)&spare32[4]                                                 ,  96, WORD32_TYPE },
{(word32 *)&flr_nvm_fcrm.errexs[0]                                     , 100, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[1]                                     , 104, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[2]                                     , 108, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[3]                                     , 112, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[4]                                     , 116, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[5]                                     , 120, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[6]                                     , 124, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[7]                                     , 128, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[8]                                     , 132, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[9]                                     , 136, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[10]                                    , 140, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[11]                                    , 144, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[12]                                    , 148, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[13]                                    , 152, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[14]                                    , 156, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[15]                                    , 160, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[16]                                    , 164, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[17]                                    , 168, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[18]                                    , 172, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[19]                                    , 176, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[20]                                    , 180, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[21]                                    , 184, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[22]                                    , 188, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[23]                                    , 192, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[24]                                    , 196, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[25]                                    , 200, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[26]                                    , 204, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[27]                                    , 208, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[28]                                    , 212, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[29]                                    , 216, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[30]                                    , 220, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[31]                                    , 224, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[32]                                    , 228, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[33]                                    , 232, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[34]                                    , 236, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[35]                                    , 240, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[36]                                    , 244, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[37]                                    , 248, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[38]                                    , 252, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[39]                                    , 256, BIT32_TYPE  },
{(word32 *)&flr_nvm_fcrm.errexs[40]                                    , 260, BIT32_TYPE  },
{(word32 *)&spare32[5]                                                 , 264, WORD32_TYPE },
{(word32 *)&spare32[6]                                                 , 268, WORD32_TYPE },
{(word32 *)&spare32[7]                                                 , 272, WORD32_TYPE },
{(word32 *)&spare32[8]                                                 , 276, WORD32_TYPE },
{(word32 *)&spare32[9]                                                 , 280, WORD32_TYPE },
{(word32 *)&spare32[10]                                                , 284, WORD32_TYPE },
{(word32 *)&spare32[11]                                                , 288, WORD32_TYPE },
{(word32 *)&spare32[12]                                                , 292, WORD32_TYPE },
{(word16 *)&rcv_req_on                                                 , 296, WORD16_TYPE },
{(word16 *)&rcv_ing                                                    , 298, WORD16_TYPE },
{(word32 *)&io_dinp_word0                                              , 300, BIT32_TYPE  },
{(word32 *)&io_dinp_word1                                              , 304, BIT32_TYPE  },
{(word32 *)&io_dinp_word2                                              , 308, BIT32_TYPE  },
{(word32 *)&io_dinp_word3                                              , 312, BIT32_TYPE  },
{(word32 *)&io_dinp_word4                                              , 316, BIT32_TYPE  },
{(word16 *)&ccdl_buf[CCDL_A_LCLS +(LDLTWOWSW>> 4)]                     , 320, BIT16_TYPE  },
{(word16 *)&ccdl_buf[CCDL_B_LCLS +(LDLTWOWSW>> 4)]                     , 322, BIT16_TYPE  },
{(word16 *)&ccdl_buf[CCDL_C_LCLS +(LDLTWOWSW>> 4)]                     , 324, BIT16_TYPE  },
{(word16 *)&ccdl_buf[CCDL_D_LCLS +(LDLTWOWSW>> 4)]                     , 326, BIT16_TYPE  },
{(word32 *)&spare32[13]                                                , 328, WORD32_TYPE },
{(int16 *)&m_ialtref                                                   , 332, INT16_TYPE  },
{(int16 *)&d_iinalt                                                    , 334, INT16_TYPE  },
{(word32 *)&mfdcsta1                                                   , 336, BIT32_TYPE  },
{(word32 *)&mfdcsta2                                                   , 340, BIT32_TYPE  },
{(word32 *)&mfdcsta3                                                   , 344, BIT32_TYPE  },
{(word32 *)&mmlf1                                                      , 348, BIT32_TYPE  },
{(word32 *)&mmlf2                                                      , 352, BIT32_TYPE  },
{(word32 *)&mmlf3                                                      , 356, BIT32_TYPE  },
{(word32 *)&mmlf4                                                      , 360, BIT32_TYPE  },
{(word32 *)&mmlf5                                                      , 364, BIT32_TYPE  },
{(word32 *)&mmlf6                                                      , 368, BIT32_TYPE  },
{(word32 *)&mmlf7                                                      , 372, BIT32_TYPE  },
{(word32 *)&mmlf8                                                      , 376, BIT32_TYPE  },
{(word32 *)&mmlf9                                                      , 380, BIT32_TYPE  },
{(word32 *)&spare32[14]                                                , 384, WORD32_TYPE },
{(word32 *)&spare32[15]                                                , 388, WORD32_TYPE },
{(word32 *)&spare32[16]                                                , 392, WORD32_TYPE },
{(word16 *)&acon_data_err                                              , 396, BIT16_TYPE  },
{(word16 *)&v_vdlmwdopen                                               , 398, WORD16_TYPE },
{(word16 *)&v_vdlmwdclsd                                               , 400, WORD16_TYPE },
{(word16 *)&v_vdrmwdopen                                               , 402, WORD16_TYPE },
{(word16 *)&v_vdrmwdclsd                                               , 404, WORD16_TYPE },
{(word16 *)&v_vdlswdopen                                               , 406, WORD16_TYPE },
{(word16 *)&v_vdlswdclsd                                               , 408, WORD16_TYPE },
{(word16 *)&v_vdrswdopen                                               , 410, WORD16_TYPE },
{(word16 *)&v_vdrswdclsd                                               , 412, WORD16_TYPE },
{(word16 *)&v_vdlswdext                                                , 414, WORD16_TYPE },
{(word16 *)&v_vdlswdret                                                , 416, WORD16_TYPE },
{(word16 *)&v_vdrswdext                                                , 418, WORD16_TYPE },
{(word16 *)&v_vdrswdret                                                , 420, WORD16_TYPE },
{(word16 *)&spare32[17]                                                , 422, WORD16_TYPE },
{(word16 *)&ccdl_buf[CCDL_A_LCLS + VBRANCH]                            , 424, WORD16_TYPE },
{(word16 *)&ccdl_buf[CCDL_B_LCLS + VBRANCH]                            , 426, WORD16_TYPE },
{(word16 *)&ccdl_buf[CCDL_C_LCLS + VBRANCH]                            , 428, WORD16_TYPE },
{(word16 *)&ccdl_buf[CCDL_D_LCLS + VBRANCH]                            , 430, WORD16_TYPE },
{(int16 *)&v_vdconf1                                                   , 432, INT16_TYPE  },
{(int16 *)&v_vdconf2                                                   , 434, INT16_TYPE  },
{(word16 *)&dloextank_ram.signal_status                                , 436, BIT16_TYPE  },
{(int16 *)&v_vdloextank                                                , 438, INT16_TYPE  },
{(word16 *)&dliextank_ram.signal_status                                , 440, BIT16_TYPE  },
{(int16 *)&v_vdliextank                                                , 442, INT16_TYPE  },
{(word16 *)&droextank_ram.signal_status                                , 444, BIT16_TYPE  },
{(int16 *)&v_vdroextank                                                , 446, INT16_TYPE  },
{(word16 *)&driextank_ram.signal_status                                , 448, BIT16_TYPE  },
{(int16 *)&v_vdriextank                                                , 450, INT16_TYPE  },
{(word16 *)&cfmn_conf_lim                                              , 452, WORD16_TYPE },
{(word16 *)&spare16[25]                                                , 454, WORD16_TYPE },
{(word32 *)&fti_dis32                                                  , 456, WORD32_TYPE },
{(int16 *)&dmddisw_state                                               , 460, INT16_TYPE  },
{(int16 *)&dvsbretd_state                                              , 462, INT16_TYPE  },
{(word16 *)&spare16[26]                                                , 464, WORD16_TYPE },
{(int16 *)&dalsw_cut_cnt[0]                                            , 466, INT16_TYPE  },
{(int16 *)&dalsw_cut_cnt[1]                                            , 468, INT16_TYPE  }};

bau_pkg_element const FCRM_FTI5[93] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE },
{(word16 *)&v_imsagcassw                                               ,  32, WORD16_TYPE },
{(word16 *)&v_iautopu_sw                                               ,  34, WORD16_TYPE },
{(word16 *)&v_iautopull_eng_req                                        ,  36, WORD16_TYPE },
{(word16 *)&autopull_fail_state                                        ,  38, WORD16_TYPE },
{(word16 *)&autopull_dl_state                                          ,  40, WORD16_TYPE },
{(word16 *)&autopull_clawsihigh                                        ,  42, WORD16_TYPE },
{(word16 *)&cord_verify[0]                                             ,  44, WORD16_TYPE },
{(word16 *)&cord_verify[1]                                             ,  46, WORD16_TYPE },
{(word16 *)&cord_verify[2]                                             ,  48, WORD16_TYPE },
{(word16 *)&cord_verify[3]                                             ,  50, WORD16_TYPE },
{(word32 *)&agcas_valid_fti                                            ,  52, WORD32_TYPE },
{(word16 *)&agcas_sw_fti                                               ,  56, WORD16_TYPE },
{(word16 *)&scan_ODCounter                                             ,  58, WORD16_TYPE },
{(word16 *)&ainsgnsalt_agcas_ram.flr_cnt[0]                            ,  60, WORD16_TYPE },
{(word16 *)&ainsgnsalt_agcas_ram.flr_cnt[1]                            ,  62, WORD16_TYPE },
{(word16 *)&ainslongitude_ram.flr_cnt[0]                               ,  64, WORD16_TYPE },
{(word16 *)&ainslongitude_ram.flr_cnt[1]                               ,  66, WORD16_TYPE },
{(word16 *)&ainslatitude_ram.flr_cnt[0]                                ,  68, WORD16_TYPE },
{(word16 *)&ainslatitude_ram.flr_cnt[1]                                ,  70, WORD16_TYPE },
{(word16 *)&stat_calc_counter                                          ,  72, WORD16_TYPE },
{(word16 *)&autopu_altfail_cnt                                         ,  74, WORD16_TYPE },
{(word32 *)&v_iinslongitude                                            ,  76, WORD32_TYPE },
{(word32 *)&v_iinslatitude                                             ,  80, WORD32_TYPE },
{(word16 *)&v_iinsgnsalt_agcas                                         ,  84, WORD16_TYPE },
{(word16 *)&v_iamach                                                   ,  86, WORD16_TYPE },
{(word16 *)&v_igndtrka                                                 ,  88, WORD16_TYPE },
{(word16 *)&v_igama                                                    ,  90, WORD16_TYPE },
{(word16 *)&ag_imgndtta                                                ,  92, WORD16_TYPE },
{(word16 *)&scan_area_verify                                           ,  94, WORD16_TYPE },
{(word16 *)&v_imaxhigh                                                 ,  96, WORD16_TYPE },
{(word16 *)&v_ihleft                                                   ,  98, WORD16_TYPE },
{(word16 *)&v_ihright                                                  , 100, WORD16_TYPE },
{(word16 *)&scan_mtype_gap_fb                                          , 102, WORD16_TYPE },
{(word16 *)&scan_pts_fb                                                , 104, WORD16_TYPE },
{(word16 *)&spare16[20]                                                , 106, WORD16_TYPE },
{(word32 *)&scan_selected_long_fb                                      , 108, WORD32_TYPE },
{(word32 *)&scan_selected_lat_fb                                       , 112, WORD32_TYPE },
{(word16 *)&v_iiahstd12s                                               , 116, WORD16_TYPE },
{(word16 *)&v_ihigh[0]                                                 , 118, WORD16_TYPE },
{(word16 *)&v_ihigh[1]                                                 , 120, WORD16_TYPE },
{(word16 *)&v_ihigh[2]                                                 , 122, WORD16_TYPE },
{(word16 *)&v_ihigh[3]                                                 , 124, WORD16_TYPE },
{(word16 *)&v_ihigh[4]                                                 , 126, WORD16_TYPE },
{(word16 *)&v_ihigh[5]                                                 , 128, WORD16_TYPE },
{(word16 *)&v_ihigh[6]                                                 , 130, WORD16_TYPE },
{(word16 *)&v_ihigh[7]                                                 , 132, WORD16_TYPE },
{(word16 *)&v_ihigh[8]                                                 , 134, WORD16_TYPE },
{(word16 *)&v_ihigh[9]                                                 , 136, WORD16_TYPE },
{(word16 *)&v_ihigh[10]                                                , 138, WORD16_TYPE },
{(word16 *)&v_ihigh[11]                                                , 140, WORD16_TYPE },
{(word16 *)&v_ihigh[12]                                                , 142, WORD16_TYPE },
{(word16 *)&v_ihigh[13]                                                , 144, WORD16_TYPE },
{(word16 *)&v_ihigh[14]                                                , 146, WORD16_TYPE },
{(word16 *)&v_ihigh[15]                                                , 148, WORD16_TYPE },
{(word16 *)&v_ihigh[16]                                                , 150, WORD16_TYPE },
{(word16 *)&v_ihigh[17]                                                , 152, WORD16_TYPE },
{(word16 *)&v_ihigh[18]                                                , 154, WORD16_TYPE },
{(word16 *)&v_ihigh[19]                                                , 156, WORD16_TYPE },
{(word16 *)&v_ihigh[20]                                                , 158, WORD16_TYPE },
{(word16 *)&v_ihigh[21]                                                , 160, WORD16_TYPE },
{(word16 *)&v_ihigh[22]                                                , 162, WORD16_TYPE },
{(word16 *)&v_ihigh[23]                                                , 164, WORD16_TYPE },
{(word16 *)&v_ihigh[24]                                                , 166, WORD16_TYPE },
{(word16 *)&v_iscanalt[0]                                              , 168, WORD16_TYPE },
{(word16 *)&v_iscanalt[1]                                              , 170, WORD16_TYPE },
{(word16 *)&v_iscanalt[2]                                              , 172, WORD16_TYPE },
{(word16 *)&v_iscanalt[3]                                              , 174, WORD16_TYPE },
{(word16 *)&v_iscanalt[4]                                              , 176, WORD16_TYPE },
{(word16 *)&v_iscanalt[5]                                              , 178, WORD16_TYPE },
{(word16 *)&v_iscanalt[6]                                              , 180, WORD16_TYPE },
{(word16 *)&v_iscanalt[7]                                              , 182, WORD16_TYPE },
{(word16 *)&v_iscanalt[8]                                              , 184, WORD16_TYPE },
{(word16 *)&v_iscanalt[9]                                              , 186, WORD16_TYPE },
{(word16 *)&v_iscanalt[10]                                             , 188, WORD16_TYPE },
{(word16 *)&v_iscanalt[11]                                             , 190, WORD16_TYPE },
{(word16 *)&v_iscanalt[12]                                             , 192, WORD16_TYPE },
{(word16 *)&v_iscanalt[13]                                             , 194, WORD16_TYPE },
{(word16 *)&v_iscanalt[14]                                             , 196, WORD16_TYPE },
{(word16 *)&v_iscanalt[15]                                             , 198, WORD16_TYPE },
{(word16 *)&v_iscanalt[16]                                             , 200, WORD16_TYPE },
{(word16 *)&v_iscanalt[17]                                             , 202, WORD16_TYPE },
{(word16 *)&v_iscanalt[18]                                             , 204, WORD16_TYPE },
{(word16 *)&v_iscanalt[19]                                             , 206, WORD16_TYPE },
{(word16 *)&v_iscanalt[20]                                             , 208, WORD16_TYPE },
{(word16 *)&v_iscanalt[21]                                             , 210, WORD16_TYPE },
{(word16 *)&v_iscanalt[22]                                             , 212, WORD16_TYPE },
{(word16 *)&v_iscanalt[23]                                             , 214, WORD16_TYPE },
{(word16 *)&v_iscanalt[24]                                             , 216, WORD16_TYPE },
{(word16 *)&ins_bussc_enable                                           , 218, WORD16_TYPE },
{(word16 *)&ins_bussc_cnt                                              , 220, WORD16_TYPE }};

bau_pkg_element * const totalbaupkg0[5] = { 
    (bau_pkg_element *)FCRM_FTI1, 
    (bau_pkg_element *)FCRM_FTI2, 
    (bau_pkg_element *)FCRM_FTI3, 
    (bau_pkg_element *)FCRM_FTI4, 
    (bau_pkg_element *)FCRM_FTI5 };
int const totalbaupkgnum0[5] = { 
206, 218, 220, 148, 93 };
word16* const totalbaupkgdesaddr0[5] = { 
    (word16 *)&ccdl_buf[CC_FCRM_OUT_FTI1],
    (word16 *)&ccdl_buf[CC_FCRM_OUT_FTI2],
    (word16 *)&ccdl_buf[CC_FCRM_OUT_FTI3],
    (word16 *)&ccdl_buf[CC_FCRM_OUT_FTI4],
    (word16 *)&ccdl_buf[CC_FCRM_OUT_FTI5]};

/* 第1套方案数据 */

bau_pkg_element const FCRM_FTI6[3] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE }};

bau_pkg_element * const totalbaupkg1[1] = { 
    (bau_pkg_element *)FCRM_FTI6 };
int const totalbaupkgnum1[1] = { 3 };
word16* const totalbaupkgdesaddr1[1] = { 
    (word16 *)&ccdl_buf[CC_FCRM_FAKE_FTIOUT]};

/* 第2套方案数据 */

bau_pkg_element const FCRM_FTI7[3] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE }};

bau_pkg_element * const totalbaupkg2[1] = { 
    (bau_pkg_element *)FCRM_FTI7 };
int const totalbaupkgnum2[1] = { 3 };
word16* const totalbaupkgdesaddr2[1] = { 
    (word16 *)&ccdl_buf[CC_FCRM_FAKE_FTIOUT]};

/* 第3套方案数据 */

bau_pkg_element const FCRM_FTI8[3] = {
{(word16 *)&fti_num                                                    ,  24, WORD16_TYPE },
{(word16 *)&sw_version                                                 ,  26, WORD16_TYPE },
{(word32 *)&fcrm_sys_ccount                                            ,  28, WORD32_TYPE }};

bau_pkg_element * const totalbaupkg3[1] = { 
    (bau_pkg_element *)FCRM_FTI8 };
int const totalbaupkgnum3[1] = { 3 };
word16* const totalbaupkgdesaddr3[1] = { 
    (word16 *)&ccdl_buf[CC_FCRM_FAKE_FTIOUT]};
/* 全部的FTI表指针 */
bau_pkg_element * const totalftipkg[4]={
    (bau_pkg_element *)totalbaupkg0,
    (bau_pkg_element *)totalbaupkg1,
    (bau_pkg_element *)totalbaupkg2,
    (bau_pkg_element *)totalbaupkg3
};
int * const totalftinum[4]={
    (int *)totalbaupkgnum0,
    (int *)totalbaupkgnum1,
    (int *)totalbaupkgnum2,
    (int *)totalbaupkgnum3
};
word16* const totalftiaddr[4] = {
    (word16 *)totalbaupkgdesaddr0,
    (word16 *)totalbaupkgdesaddr1,
    (word16 *)totalbaupkgdesaddr2,
    (word16 *)totalbaupkgdesaddr3
};
int const totalftitablenum[4]={5, 1, 1, 1 };
