#ifndef FCRM_CLAW_ROM_VDCL_H_
#define FCRM_CLAW_ROM_VDCL_H_
#define  VTYP_FCRM_CLAW_RAM16_LST(x)   word16 *const    x[]
#define  VDCL_FCRM_CLAW_RAM16_LST    extern   VTYP_FCRM_CLAW_RAM16_LST(FCRM_CLAW_RAM16_LST)

#define  VTYP_FCRM_CLAW_RAM32_LST(x)   word32 *const    x[]
#define  VDCL_FCRM_CLAW_RAM32_LST    extern   VTYP_FCRM_CLAW_RAM32_LST(FCRM_CLAW_RAM32_LST)

#endif /*FCRM_CLAW_ROM_VDCL_H_*/
